# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
/control/verbose 2
#
/run/verbose 2
/event/verbose 2 
#/tracking/verbose 1
# 
# world is unlimited visible
/vis/geometry/set/visibility World -1 true
# 
# proton 10 MeV to random direction 
#
/gun/particle proton
/gun/energy 10 MeV
/gun/position 0 0 0
/tracking/verbose 2
#
/run/beamOn 10
