#ifndef DaliGlobals_h
#define DaliGlobals_h

//FOR RISING:
#define NUMBEROFCLUSTERDETECTORS 15
#define NUMBEROFMINIBALLDETECTORS 8
#define NUMBEROFHECTORDETECTORS 8

// For the RIBF
#define NUMBEROFSHOGUNCRYSTALS 1200
#define NUMBEROFSHOGUNADDBACKCRYSTALS 50
#define NUMBEROFDALI2CRYSTALS 186 
#define NUMBEROFDALI2ADDBACKCRYSTALS 130
#define NUMBEROFLABR3ARRAYCRYSTALS 8
#define NUMBEROFGRAPEDETECTORS 18
#define NUMBEROFSGTDETECTORS 10 

#endif
 
